# Generated by Django 5.1.2 on 2024-11-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galaxie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='number_of_seats',
            field=models.IntegerField(),
        ),
    ]
